version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  app:
    build: .
    command: npm start
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - rabbitmq
    env_file:
      - .env
    links:
      - rabbitmq
networks:
  app-network:
    driver: bridge